apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: api
        env:
          - name: CHALLENGE_PATH
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: challenge_path
          - name: CHALLENGE_VAL
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: challenge_value
          - name: MNT_PATH
            valueFrom:
              configMapKeyRef:
                name: env-map
                key: mnt_path
        image: {{ printf "%s:%s" .Values.app.image.name .Values.app.image.tag }}
        volumeMounts:
          - mountPath: {{ .Values.app.mount }}
            name: volume
        ports:
        - containerPort: 8080
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: simple-api-azurefile

