apiVersion: v1
kind: Service
metadata:
  name: simple-api-svc
spec:
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.app.port }}
