apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
      - name: api
        image: {{ printf "%s:%s" .Values.app.image.name .Values.app.image.tag }}
        ports:
        - containerPort: 8080


