apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: api-gateway
  namespace: istio-system
spec:
  selector:
    app: istio-ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: simple-api-credential

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-route
spec:
  hosts:
  - "*"
  gateways:
      - istio-system/api-gateway
  http:
  - name: "api-routes"
    route:
    - destination:
        host: simple-api-svc.default.svc.cluster.local
        port:
          number: 80
